<?php

module_load_include('inc', 'bxdev_comment', 'bxdev_comment.forms');

/**
 * HOOKS
 */

/**
 * Implements hook_init().
 */
function bxdev_comment_init() {
	// check if a node display page (not edit or admin)
	$arg2 = arg(2);
	if(arg(0) == 'node' && is_numeric(arg(1)) && empty($arg2)){
		$node = node_load(arg(1));
		if($node->type == 'project'){
			drupal_add_js(drupal_get_path('module', 'bxdev_comment') . '/bxdev_comment.js');
			drupal_add_css(drupal_get_path('module', 'bxdev_comment') . '/bxdev_comment.css');
			// we must load the form here to ensure the form messages are rendered at the proper time
			drupal_get_form('bxdev_comment_client_form');
			drupal_get_form('bxdev_comment_videographer_form');
		}
	}
}

/**
 * Implements hook_permission().
 */
function bxdev_comment_permission() {
  return array(
    'approve client revision list' =>  array(
      'title' => t('Approve client revision list'),
      'description' => t('Approve client revision list.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bxdev_comment_menu() {
  $items['comment/approve/client/%node/%'] = array(
    'page callback' => 'bxdev_comment_revision_approve_client',
		'page arguments' => array(3, 4),
    'access arguments' => array('approve client revision list'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
function bxdev_comment_preprocess_node(&$vars){	
	$node = $vars['node'];	
  switch($node->type){
  	case 'project':

			$project = new Project($node->nid);
			
			// if a spec video, disable commenting
			if($project->project->field_video_type['und'][0]['value'] == 'spec'){
				
				$vars['spec_intro'] = '
					<div class="spec-intro">
						<h1>Welcome to Lightswitch!</h1>
						<p>We\'ve created a video showcasing your business for our local directory and thought you\'d like to see it.  Click on the play button to view.  After you\'ve watched, scroll down below your video to see some beautiful high resolution photos of your business that were captured during the shoot.</p>
					</div>
				';
				
				$vars['spec_markup1'] = '
					<div class="why-tabs">
						<h2>Why your business needs video:</h2>
						<p>Video is one of the most cost effective ways to take your online marketing to the next level. Check out the reasons why our clients choose us to produce videos that increase their online presence and bring in new customers.</p>
						<div id="block-1">
							<div class="col c1">
								<h4>Search for Local Business Starts Online</h4>
								<div class="img-wrap"><img src="/sites/all/themes/bms/images/spec_google.jpg"/></div>
								<p><strong>74%</strong> of internet users perform local searches</p>
								<p><strong>61%</strong> of those searches result in a store purchase</p>
							</div>  
							<div class="col c2">
								<h4>Improve Rankings</h4>
								<div class="img-wrap"><img src="/sites/all/themes/bms/images/spec_engines.jpg"/></div>
								<p>Sites containing video are <strong>53x</strong> more likely to appear on the first page of Google results</p>
							</div>
							<div class="col c3">
								<h4>Engage Users</h4>
								<div class="img-wrap"><img src="/sites/all/themes/bms/images/spec_share.jpg"/></div>
								<p>Video landing pages generate <strong>5x</strong> higher engagement and response rates</p>
							</div>
							<div class="col c4">
								<h4>Convert Customers</h4>
								<div class="img-wrap"><img src="/sites/all/themes/bms/images/spec_money.jpg"/></div>
								<p><strong>41%</strong> of people take action after watching a video</p>
							</div>
						</div>
					</div>';
					
					$vars['spec_markup2'] = '<div class="block">
						<h2>Do you love your video?</h2>
						<p>Many local directory participants decide to purchase their video after watching the preview for a one-time fee of $449.</p>
						<h2>Here\'s how it works:</h2>
						<p>- You provide feedback and we\'ll make one round of edits for free<br>
						- We remove all Lightswitch branding from the video<br>
						- We deliver a final video in a convenient file format<br>
						- You own full rights to the video and can use it on any of your online marketing pages"</p>
						<p><strong>If you are interested, click the "Contact Me" button and one of our team members will get in touch within the next two days.</strong></p>
						<p class="btn-wrap"><a href="/project/spec/contact/' . $project->project->nid . '" class="btn-contact">Contact Me</a></p>
					</div>';
				
			// if not a spec video, enable commenting
			}else{
			
				if(user_access('pc')){
					$vars['comment_switch'] = '<div class="comment-switch"><a href="" class="client-switch active">Client</a><a href="" class="videographer-switch">Videographer</a></div>';
				}
			
				// if client or pc
				if(user_access('client') || user_access('pc')){
					// get the client comments view
					$vars['client_comments'] = '<div class="client-comments-wrap">' . views_embed_view('comments', 'client');
				}
			
				// if videographer or pc
				if(user_access('videographer') || user_access('pc')){
					$pc = user_access('pc') ? 'pc' : '';
					$vars['videographer_comments'] = '<div class="videographer-comments-wrap ' . $pc . '">' . views_embed_view('comments', 'videographer');
				}
			
				// if project has not been approved
				if(!$project->approved){
					// if client or pc
					if(user_access('client') || user_access('pc')){
						// get the comment form
						$client_comment_form = render(drupal_get_form('bxdev_comment_client_form'));
						// if comments exist
						if(!empty($project->comments)){
							// get the last comment
							$last_comment = end($project->comments);
							// if the last comment is a revision list and its not approved or declined
							if($last_comment->field_revision_list['und'][0]['value'] == 1 && $last_comment->field_revision_approved['und'][0]['value'] == 0 && empty($last_comment->field_declined_reason)){
								// show the comment form
								$client_comment_form = '<div class="revision-decline-client-form">' . render(drupal_get_form('bxdev_comment_client_decline_form', $last_comment->nid)) . '</div>';
							}				
						}
						$vars['client_comment_form'] = $client_comment_form . '</div>';
					}
			
					// if videographer or pc
					if(user_access('videographer') || user_access('pc')){				
						$vars['videographer_comment_form'] = render(drupal_get_form('bxdev_comment_videographer_form')) . '</div>';
					}
			
				// project has been approved
				}else{
					$approved_html = '<div class="project-approved">This project has been approved.</div></div>';
					if(user_access('client') || user_access('pc')){
						$vars['client_comment_form'] = $approved_html;
					}
					if(user_access('videographer') || user_access('pc')){
						$vars['videographer_comment_form'] = $approved_html;
					}					
				}
			
			}
  		
  		break;
  }
}


/**
 * CUSTOM
 */

/**
 * Page callback: client approve revision list
 */
function bxdev_comment_revision_approve_client($comment_node, $project_nid){
	// set the revision approved field to true (1)
	$comment_node->field_revision_approved['und'][0]['value'] = 1;
	// set the revision approved date to now
	$comment_node->field_revision_approved_date['und'][0]['value'] = mktime();
	// add the videographer rights to the comment
	$comment_node->field_comment_type['und'][1]['value'] = 'videographer';	
	// save the comment node
	node_save($comment_node);
	// load the project object
	$project = new Project($project_nid);
	// notify pc and videog of revision approval
	$project->send_revision_approved($comment_node->nid);
	// log the action
	$project->log('admin', 'Client approved revision list');	
	// return to the project page
	drupal_goto('node/' . $project->project->nid);
}









