<?php

/**
 * HOOKS
 */

/**
 * Implements hook_views_api().
 */
function bxdev_project_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function bxdev_project_menu() {
  $items['project/%node/claim'] = array(
    'page callback' => 'bxdev_project_claim_callback',
		'page arguments' => array(1),
    'access arguments' => array('pc'),
    'type' => MENU_CALLBACK,
  );

	$items['project/%/reset/client'] = array(
		'page callback' => 'bxdev_project_reset_client_callback',
		'page arguments' => array(1),
		'access arguments' => array('pc'),
		'type' => MENU_CALLBACK,
	);
	
	$items['project/%/approve'] = array(
		'page callback' => 'bxdev_project_approve_callback',
		'page arguments' => array(1),
		'access arguments' => array('client'),
		'type' => MENU_CALLBACK,
	);
	
	$items['project/%node/download/doc'] = array(
		'page callback' => 'bxdev_project_download_production_details',
		'page arguments' => array(1),
		'access arguments' => array('view production details'),
		'type' => MENU_CALLBACK,
	);
	
	$items['project/%/photos'] = array(
		'title' => t('Photo review'),
		'page callback' => 'bxdev_project_photo_approval_page',
		'page arguments' => array(1),
		'access arguments' => array('view project photos'),
		'type' => MENU_CALLBACK,
	);	

  return $items;
}

/**
 * Implements hook_mail().
 */
function bxdev_project_mail($key, &$message, $params) {
	global $base_url;
	switch($key){
		case 'comment':
			$subject = t('A new comment has been posted in @title', array('@title' => $params['project_title']));
			$body = 'A new comment has been posted in ' . $params['project_title'] . '<br><br>';
			$body .= 'Click here to view the project:<br>' . $params['project_link'] . '<br><br>';
			$body .= 'The comment was posted at: ' . $params['comment_date'] . '<br><br>';
			$body .= 'Posted by: ' . $params['comment_author'] . '<br><br>';
			$body .= 'Comment:<br>' . nl2br($params['comment']) . '<br><br>';			
			
			$message['subject'] = $subject;
			$message['body'][] = $body;
			break;
			
		case 'approved':
			$subject = t('Congratulations, your @title video has been approved!', array('@title' => $params['project_title']));
			$body = 'You will be receiving the final video formats of your lightswitch video within 2-3 business days.<br><br>';
			$body .= 'As always, let us know if you have any questions or concerns. Thank you for your business!.<br><br>';
			$body .= 'Sincerely,<br>';
			$body .= $params['pc']['full_name'] . '<br>';
			$body .= $params['pc']['email'] . '<br>';
			$body .= $params['pc']['phone'];

			$message['subject'] = $subject;
			$message['body'][] = $body;
			break;

	}
	// make emails HTML-enabled
	$message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
}

/**
 * Implements hook_node_insert().
 */
function bxdev_project_node_insert($node) {
  switch($node->type){	
		case 'project':
			// get the business full name
			$full_name = $node->field_business_contact_name['und'][0]['value'];
			// get the business phone
			$phone = $node->field_phone['und'][0]['value'];
			// load the business node object
			$business = node_load($node->field_project_business_ref['und'][0]['nid']);
			// load the client user object
			$client = user_load($business->field_client_ref['und'][0]['uid']);
			// assign new fields to the client user
			$edit = (array)$client;
			$edit['field_name']['und'][0]['value'] = $full_name;
			$edit['field_phone']['und'][0]['value'] = $phone;
			user_save($client, $edit);
			// log action
			watchdog('lightswitch', 'New project: @title, nid: @nid', array('@title' => $node->title, '@nid' => $node->nid));
			$project = new Project($node->nid);
			$project->log('admin', 'Project added');
			$project->set_status(1);
			
			// set the business profile video default
			if(empty($business->field_profile_video_ref)){
				$business->field_profile_video_ref['und'][0]['nid'] = $node->nid;
				node_save($business);
			}
			
			break;
			
		case 'comment':
			$project = new Project($node->field_project_ref['und'][0]['nid']);
			// if the first comment
			if(count($project->comments) == 1){
				if(!$project->overridden){
					// set the status to 4 - Version 1 to Client
					$project->set_status(4);
					$project->log('admin', 'Project auto updated to 4 - Version 1 to Client');
				}
				$user = new User();
				$user->load($project->client->uid);
				$user->send_client_project_login($project->project->nid);
			}else{
				// notify all appropriate users
				$project->comment_notify($node->nid);
			}
			$client_comments = array();
			// count client's comments
			foreach($project->comments as $comment){
				if($comment->uid == $project->client->uid){
					$client_comments[] = $comment->nid;
				}
			}
			// if client has posted at least one comment, set status to 5 - Revision
			if(!empty($client_comments) && !$project->overridden){
				$project->set_status(5);
				$project->log('admin', 'Project auto updated to 5 - Revision');
			}
	}
}

/**
 * Implements hook_node_update().
 */
function bxdev_project_node_submit(&$node, $form, &$form_state) {
	$values = $form_state['values'];
	switch($node->type){
		case 'project':
		
		  $project = new Project($node->nid);
			$old_status = $project->get_status();			
			$new_status = $values['field_status']['und'][0]['value'];
			
			// detect if manually overridden
			if($old_status !== $new_status){
				$node->field_status_date['und'][0]['value'] = time();
				$node->field_status_override['und'][0]['value'] = 1;
			}
			
			// check if project is currently status 2 (claimed), a videographer has been assigned, and project is not manually overridden
			if($project->get_status() == 2 && !empty($node->field_videog_ref['und']) && $node->field_status_override['und'][0]['value'] !== 1){
				// set status to 3 (assigned)
				$node->field_status['und'][0]['value'] = 3;
				$project->log('admin', 'Project auto updated to 3 - Assigned');
			}
			break;			
	}
}

/**
 * Implements hook_preprocess_node().
 */
function bxdev_project_preprocess_node(&$vars){
	if($vars['type'] == 'project'){
		
		// include for the node add form
		module_load_include('inc', 'node', 'node.pages');
		
		// load up some variables
		global $user;
		$role = bxdev_user_get_role($user->uid);
		$profile = '';		
		$nid = $vars['nid'];
		$project = new Project($nid);
		$content = node_view($project->project);
		$comment_permission = TRUE;
		
		// if videographer role, get the profile
		if($role == 'videographer'){
			$profile = profile2_load_by_user($user->uid, 'videographer');
		}
		
		// send the objects to the tpl
		$vars['business'] = $project->business;
		$vars['client'] = $project->client;
		$vars['pc'] = $project->pc;
		$vars['videographer'] = $project->videographer;
		
		// check if project has been approved
		$vars['approved'] = $vars['field_approved'][0]['value'];
		
		// check commenting permissions
		if($role == 'videographer' && !$profile->field_post_comments['und'][0]['value']){
			$comment_permission = FALSE;
		}
		$vars['comment_permission'] = $comment_permission;
		
		// get the comment add form
		$comment_form = '<h2>Post a Comment:</h2>';
		$comment_form .= drupal_render(node_add('comment'));
		$vars['comment_form'] = $comment_form;
		
		// get the comments
		$vars['comments'] = views_embed_view('comments', 'block');
		
		// approve button
		if(bxdev_user_get_role($user->uid) == 'client'){
			$approve_button = '<span class="approve-or">or</span> <a class="approve-btn" href="">Approve</a>';
			$approve_button .= '<div class="approve-confirm" style="display:none;"><h3>Are you sure you wish to approve this project?</h3><p>After approval, comments will no longer be able to be posted.</p><a class="approve-yes" href="/project/' . $nid . '/approve">Approve</a> <a href="" class="approve-cancel">Cancel</a></div>';
			$vars['approve_button'] = $approve_button;
		}
		
		// production details
		if(user_access('view production details')){
			$production_details = '<div class="block prod-details-wrap">
				<div class="download-doc"><a href="/project/' . $nid . '/download/doc">Download Word Doc</a></div>
				<div class="download-doc"><a href="/sites/default/files/LS_Production_Release.docx">Download Release</a></div>
				<div class="trigger">
					<h2>Production Details</h2>
				</div>
				<div class="trigger-list prod-details">';
			$production_details .= (isset($content['field_shoot_date'])) ? render($content['field_shoot_date']) : '';
			$production_details .= (isset($content['field_voice_over'])) ? render($content['field_voice_over']) : '';
			$production_details .= (isset($content['field_voice_over_gender'])) ? render($content['field_voice_over_gender']) : '';
			$production_details .= (isset($content['field_owner_interview'])) ? render($content['field_owner_interview']) : '';
			$production_details .= (isset($content['field_script_notes'])) ? render($content['field_script_notes']) : '';
			$production_details .= (isset($content['field_logo'])) ? render($content['field_logo']) : '';
			$production_details .= (isset($content['field_photos'])) ? render($content['field_photos']) : '';
			$production_details .= (isset($content['field_features_include'])) ? render($content['field_features_include']) : '';
			$production_details .= (isset($content['field_features_avoid'])) ? render($content['field_features_avoid']) : '';
			$production_details .= (isset($content['field_unique'])) ? render($content['field_unique']) : '';
			$production_details .=	'</div></div>';
			$vars['production_details'] = $production_details;
		}		
		
		// production history
		if(user_access('view production history')){
			$vars['production_history'] = bxdev_project_get_production_log($nid);
		}
		
	  // if user is sales or pc, allow edit / delete
		if(user_access('sales') || user_access('pc')){
			$operations = '<div class="edit"><a href="/node/' . $vars['node']->nid . '/edit">Edit</a></div>';
			$operations .= '<div class="delete"><a href="/node/' . $vars['node']->nid . '/delete">Delete</a></div>';
			$vars['operations'] = $operations;
		}
						
		// photos
		
		// get renderable arrays
		$project_full = node_view($project->project, 'full');
		$project_teaser = node_view($project->project, 'teaser');
		
		// get approved photos
		$results = db_query("SELECT fid FROM {project_photos_approval} WHERE nid = :nid", array(':nid' => $nid));
		$approved_photos = array();
		if($results->rowCount() > 0){
			foreach($results as $row){
				$approved_photos[] = $row->fid;
			}
		}
		
		// if approved photos exist
		$approved_photos = $project->get_approved_photos();
		$photos_teaser = '<div class="clearfix">';
		$photos = array();
		// cycle through each project photo
		foreach($project_full['field_project_photos'] as $key => $value){
			// if photo
			if(is_numeric($key)){
				// if approved
				if(in_array($value['#item']['fid'], $approved_photos)){
					// get the teaser photo
					$photos_teaser .= '<div class="project-thumb"><a rel="shadowbox" href="' . image_style_url('approval', $value['#item']['uri']) . '">' . theme('image_style', array('path' => $value['#item']['uri'], 'style_name' => 'project_thumb')) . '</a></div>';
				}
			}
		}
		$photos_teaser .= '</div>';
		$vars['photos_teaser'] = $photos_teaser;
		
		// business logo upload
		if(user_access('upload business logo')){
			$vars['business_logo_upload'] = render(drupal_get_form('bxdev_project_logo_upload_form'));
		}
		
		// videographer documents
		if(user_access('upload videographer documents')){
			$vars['videographer_documents'] = render(drupal_get_form('bxdev_project_videographer_documents_form'));
		}
		
	}
}


/**
 * FORMS
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bxdev_project_form_comment_node_form_alter(&$form, $form_state){
	// change submit button
	$form['actions']['submit']['#value'] = t('Post Comment');
	// hide the title field
	$form['title']['#type'] = 'hidden';
	$form['title']['#value'] = NULL;
	// hide the comment label
	$form['field_comment']['und'][0]['value']['#title'] = '';
	$form['field_comment']['und'][0]['value']['#default_value'] = t('Type your comments here...');
	// hide the project ref field
	$form['field_project_ref']['#type'] = 'hidden';
	// add custom validate handler
	array_unshift($form['#validate'], 'bxdev_project_comment_node_form_validate'); 
	// add custom submit handler
	$form['actions']['submit']['#submit'][] = 'bxdev_project_comment_node_form_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bxdev_project_form_project_node_form_alter(&$form, $form_state){
	// add custom validation handler
	$form['actions']['submit']['#validate'][] = 'bxdev_project_form_project_node_form_validate';
	// hide the original date field
	$form['field_shoot_date']['#type'] = 'hidden';
	// create a fieldset
	$form['bxdev_shoot_date_fieldset'] = array(
		'#type' => 'fieldset',
		'#weight' => 13,
		'#attributes' => array(
			'class' => array('clearfix'),
		),
	);
	// create a custom date field
	$form['bxdev_shoot_date_fieldset']['bxdev_shoot_date'] = array(
		'#type' => 'textfield',
		'#title' => t('Shoot date'),
		'#default_value' => (!empty($form['field_shoot_date']['und'][0]['#default_value']['value'])) ? date('m/d/Y', $form['field_shoot_date']['und'][0]['#default_value']['value']) : '',
	);
	// create a custom start time field
	$form['bxdev_shoot_date_fieldset']['bxdev_shoot_time1'] = array(
		'#title' => t('Start time'),
		'#type' => 'select',
		'#options' => array(
			'0:00' => '12:00am',
			'0:15' => '12:15am',
			'0:30' => '12:30am',
			'0:45' => '12:45am',
			'1:00' => '1:00am',
			'1:15' => '1:15am',
			'1:30' => '1:30am',
			'1:45' => '1:45am',
			'2:00' => '2:00am',
			'2:15' => '2:15am',
			'2:30' => '2:30am',
			'2:45' => '2:45am',
			'3:00' => '3:00am',
			'3:15' => '3:15am',
			'3:30' => '3:30am',
			'3:45' => '3:45am',
			'4:00' => '4:00am',
			'4:15' => '4:15am',
			'4:30' => '4:30am',
			'4:45' => '4:45am',
			'5:00' => '5:00am',
			'5:15' => '5:15am',
			'5:30' => '5:30am',
			'5:45' => '5:45am',
			'6:00' => '6:00am',
			'6:15' => '6:15am',
			'6:30' => '6:30am',
			'6:45' => '6:45am',
			'7:00' => '7:00am',
			'7:15' => '7:15am',
			'7:30' => '7:30am',
			'7:45' => '7:45am',
			'8:00' => '8:00am',
			'8:15' => '8:15am',
			'8:30' => '8:30am',
			'8:45' => '8:45am',
			'9:00' => '9:00am',
			'9:15' => '9:15am',
			'9:30' => '9:30am',
			'9:45' => '9:45am',
			'10:00' => '10:00am',
			'10:15' => '10:15am',
			'10:30' => '10:30am',
			'10:45' => '10:45am',
			'11:00' => '11:00am',
			'11:15' => '11:15am',
			'11:30' => '11:30am',
			'11:45' => '11:45am',
			'12:00' => '12:00pm',
			'12:15' => '12:15pm',
			'12:30' => '12:30pm',
			'12:45' => '12:45pm',
			'13:00' => '1:00pm',
			'13:15' => '1:15pm',
			'13:30' => '1:30pm',
			'13:45' => '1:45pm',
			'14:00' => '2:00pm',
			'14:15' => '2:15pm',
			'14:30' => '2:30pm',
			'14:45' => '2:45pm',
			'15:00' => '3:00pm',
			'15:15' => '3:15pm',
			'15:30' => '3:30pm',
			'15:45' => '3:45pm',
			'16:00' => '4:00pm',
			'16:15' => '4:15pm',
			'16:30' => '4:30pm',
			'16:45' => '4:45pm',
			'17:00' => '5:00pm',
			'17:15' => '5:15pm',
			'17:30' => '5:30pm',
			'17:45' => '5:45pm',
			'18:00' => '6:00pm',
			'18:15' => '6:15pm',
			'18:30' => '6:30pm',
			'18:45' => '6:45pm',
			'19:00' => '7:00pm',
			'19:15' => '7:15pm',
			'19:30' => '7:30pm',
			'19:45' => '7:45pm',
			'20:00' => '8:00pm',
			'20:15' => '8:15pm',
			'20:30' => '8:30pm',
			'20:45' => '8:45pm',
			'21:00' => '9:00pm',
			'21:15' => '9:15pm',
			'21:30' => '9:30pm',
			'21:45' => '9:45pm',
			'22:00' => '10:00pm',
			'22:15' => '10:15pm',
			'22:30' => '10:30pm',
			'22:45' => '10:45pm',
			'23:00' => '11:00pm',
			'23:15' => '11:15pm',
			'23:30' => '11:30pm',
			'23:45' => '11:45pm',			
		),
		'#default_value' => (!empty($form['field_shoot_date']['und'][0]['#default_value']['value'])) ? date('G:i', $form['field_shoot_date']['und'][0]['#default_value']['value']) : '',
	);
	// create a custom end time field
	$form['bxdev_shoot_date_fieldset']['bxdev_shoot_time2'] = array(
		'#title' => t('End time'),
		'#type' => 'select',
		'#options' => array(
			'0:00' => '12:00am',
			'0:15' => '12:15am',
			'0:30' => '12:30am',
			'0:45' => '12:45am',
			'1:00' => '1:00am',
			'1:15' => '1:15am',
			'1:30' => '1:30am',
			'1:45' => '1:45am',
			'2:00' => '2:00am',
			'2:15' => '2:15am',
			'2:30' => '2:30am',
			'2:45' => '2:45am',
			'3:00' => '3:00am',
			'3:15' => '3:15am',
			'3:30' => '3:30am',
			'3:45' => '3:45am',
			'4:00' => '4:00am',
			'4:15' => '4:15am',
			'4:30' => '4:30am',
			'4:45' => '4:45am',
			'5:00' => '5:00am',
			'5:15' => '5:15am',
			'5:30' => '5:30am',
			'5:45' => '5:45am',
			'6:00' => '6:00am',
			'6:15' => '6:15am',
			'6:30' => '6:30am',
			'6:45' => '6:45am',
			'7:00' => '7:00am',
			'7:15' => '7:15am',
			'7:30' => '7:30am',
			'7:45' => '7:45am',
			'8:00' => '8:00am',
			'8:15' => '8:15am',
			'8:30' => '8:30am',
			'8:45' => '8:45am',
			'9:00' => '9:00am',
			'9:15' => '9:15am',
			'9:30' => '9:30am',
			'9:45' => '9:45am',
			'10:00' => '10:00am',
			'10:15' => '10:15am',
			'10:30' => '10:30am',
			'10:45' => '10:45am',
			'11:00' => '11:00am',
			'11:15' => '11:15am',
			'11:30' => '11:30am',
			'11:45' => '11:45am',
			'12:00' => '12:00pm',
			'12:15' => '12:15pm',
			'12:30' => '12:30pm',
			'12:45' => '12:45pm',
			'13:00' => '1:00pm',
			'13:15' => '1:15pm',
			'13:30' => '1:30pm',
			'13:45' => '1:45pm',
			'14:00' => '2:00pm',
			'14:15' => '2:15pm',
			'14:30' => '2:30pm',
			'14:45' => '2:45pm',
			'15:00' => '3:00pm',
			'15:15' => '3:15pm',
			'15:30' => '3:30pm',
			'15:45' => '3:45pm',
			'16:00' => '4:00pm',
			'16:15' => '4:15pm',
			'16:30' => '4:30pm',
			'16:45' => '4:45pm',
			'17:00' => '5:00pm',
			'17:15' => '5:15pm',
			'17:30' => '5:30pm',
			'17:45' => '5:45pm',
			'18:00' => '6:00pm',
			'18:15' => '6:15pm',
			'18:30' => '6:30pm',
			'18:45' => '6:45pm',
			'19:00' => '7:00pm',
			'19:15' => '7:15pm',
			'19:30' => '7:30pm',
			'19:45' => '7:45pm',
			'20:00' => '8:00pm',
			'20:15' => '8:15pm',
			'20:30' => '8:30pm',
			'20:45' => '8:45pm',
			'21:00' => '9:00pm',
			'21:15' => '9:15pm',
			'21:30' => '9:30pm',
			'21:45' => '9:45pm',
			'22:00' => '10:00pm',
			'22:15' => '10:15pm',
			'22:30' => '10:30pm',
			'22:45' => '10:45pm',
			'23:00' => '11:00pm',
			'23:15' => '11:15pm',
			'23:30' => '11:30pm',
			'23:45' => '11:45pm',			
		),
		'#default_value' => (!empty($form['field_shoot_date']['und'][0]['#default_value']['value2'])) ? date('G:i', $form['field_shoot_date']['und'][0]['#default_value']['value2']) : '',
	);
}

/**
 * Form builder: photo approval
 */
function bxdev_project_photo_approval_form($form, $form_state){
	$form = array();
	$node = node_load(arg(1));
	$render = node_view($node, 'teaser');
	$full = node_view($node, 'full');
	
	// if photos have been assigned
	if(!empty($render['field_project_photos'])){
		
		// get stored values
		$results = db_query("SELECT fid FROM {project_photos_approval} WHERE nid = :nid", array(':nid' => $node->nid));
		$defaults = array();
		if($results->rowCount() > 0){
			foreach($results as $row){
				$defaults[] = $row->fid;
			}
		}
		
		// build the images and checkboxes
		foreach($render['field_project_photos'] as $key => $value){
			if(is_numeric($key)){
				// dpm($value);
				$path = file_create_url($full['field_project_photos'][$key]['#item']['uri']);
				$form['approve'][$value['#item']['fid']] = array(
				  '#type' => 'checkbox',
				  '#title' => t('Approve'),
				  '#default_value' => in_array($value['#item']['fid'], $defaults),
					'#prefix' => '<div class="photo-wrap"><a rel="shadowbox" href="' . image_style_url('approval', $full['field_project_photos'][$key]['#item']['uri']) . '">' . theme($value['#theme'], $value) . '</a>',
					'#suffix' => '</div>',
				);				
			}
		}
		
		// submit button
		$form['submit'] = array(
		  '#type' => 'submit',
		  '#value' => t('Submit'),
		);		
		
	// photos have not been assigned
	}else{
		$form['no_photos'] = array(
			'#markup' => t('No photos assigned.'),
		);
	}
	
	return $form;
}

/**
 * Form builder: business logo
 */
function bxdev_project_logo_upload_form($form, &$form_state){
	$nid = arg(1);
	$node = node_load($nid);
	$form['business_logo'] = array(
		'#type' => 'managed_file',
		'#title' => t('Business logo'),
		'#size' => 30,
		'#default_value' => (!empty($node->field_logo['und'][0])) ? $node->field_logo['und'][0]['fid'] : '',
		'#upload_location' => 'public://business_logos',
		'#upload_validators' => array(
			'file_validate_extensions' => array('jpg jpeg gif png'),
		),
	);
	
	$form['save'] = array(
	  '#type' => 'submit',
	  '#value' => t('Save'),
	);	
	
	return $form;
}

/**
 * Form builder: videographer documents
 */
function bxdev_project_videographer_documents_form($form, &$form_state){
	$nid = arg(1);
	$node = node_load($nid);
	
	$form['signed_production_release'] = array(
		'#type' => 'managed_file',
		'#title' => t('Signed production release'),
		'#size' => 15,
		'#default_value' => (!empty($node->field_signed_production_release['und'][0])) ? $node->field_signed_production_release['und'][0]['fid'] : '',
		'#upload_location' => 'public://videographer_forms',
		'#upload_validators' => array(
			'file_validate_extensions' => array('jpg jpeg gif png pdf doc docx'),
		),
	);
	
	$form['videographer_invoice'] = array(
		'#type' => 'managed_file',
		'#title' => t('Videographer invoice'),
		'#size' => 15,
		'#default_value' => (!empty($node->field_videographer_invoice['und'][0])) ? $node->field_videographer_invoice['und'][0]['fid'] : '',
		'#upload_location' => 'public://videographer_forms',
		'#upload_validators' => array(
			'file_validate_extensions' => array('jpg jpeg gif png pdf doc docx'),
		),
	);
	
	$form['save'] = array(
	  '#type' => 'submit',
	  '#value' => t('Save'),
	);	
	
	return $form;
}

/**
 * Form submit handler: project node form
 */
function bxdev_project_form_project_node_form_validate($form, &$form_state){
	// get all the values
	$values = $form_state['values'];
	$date = $values['bxdev_shoot_date'];
	$time1 = $values['bxdev_shoot_time1'];
	$time2 = $values['bxdev_shoot_time2'];
	// convert to timestamps
	$timestamp1 = strtotime($date . ' ' . $time1);
	$timestamp2 = strtotime($date . ' ' . $time2);
	// set the original date fields
	form_set_value($form['field_shoot_date']['und'][0]['value'], $timestamp1, $form_state);
	form_set_value($form['field_shoot_date']['und'][0]['value2'], $timestamp2, $form_state);
}

/**
 * Form submit handler: business logo
 */
function bxdev_project_logo_upload_form_submit($form, &$form_state){
	$values = $form_state['values'];
	$nid = arg(1);
	$node = node_load($nid);
	// if no file, remove logo file from the node
	if(empty($values['business_logo'])){
		unset($node->field_logo['und'][0]);
		node_save($node);
	}else{
		// get the file object
		$file = file_load($values['business_logo']);
		$file->status = FILE_STATUS_PERMANENT;
		file_save($file);
		// create a file array to attach to the node
		$node_file = array(
			'uid' => $file->uid,
			'uri' => $file->uri,
			'fid' => $file->fid,
			'status' => 1,
			'display' => 1,
			'description' => '',
		);
		$node->field_logo['und'][0] = $node_file;
		node_save($node);
	}
}

/**
 * Form submit handler: videographer documents
 */
function bxdev_project_videographer_documents_form_submit($form, &$form_state){
	$values = $form_state['values'];
	$nid = arg(1);
	$node = node_load($nid);
		
	// if no file, remove logo file from the node
	if(empty($values['signed_production_release'])){
		unset($node->field_signed_production_release['und'][0]);
	}else{
		// get the file object
		$file = file_load($values['signed_production_release']);
		$file->status = FILE_STATUS_PERMANENT;
		file_save($file);
		// create a file array to attach to the node
		$node_file = array(
			'uid' => $file->uid,
			'uri' => $file->uri,
			'fid' => $file->fid,
			'status' => 1,
			'display' => 1,
			'description' => '',
		);
		$node->field_signed_production_release['und'][0] = $node_file;
	}
	
	// if no file, remove logo file from the node
	if(empty($values['videographer_invoice'])){
		unset($node->field_videographer_invoice['und'][0]);
	}else{
		// get the file object
		$file = file_load($values['videographer_invoice']);
		$file->status = FILE_STATUS_PERMANENT;
		file_save($file);
		// create a file array to attach to the node
		$node_file = array(
			'uid' => $file->uid,
			'uri' => $file->uri,
			'fid' => $file->fid,
			'status' => 1,
			'display' => 1,
			'description' => '',
		);
		$node->field_videographer_invoice['und'][0] = $node_file;
	}
	
	node_save($node);
	
}

/**
 * Form submit handler: comment node form
 */
function bxdev_project_comment_node_form_submit($form, &$form_state){
	$form_state['redirect'] = substr($_SERVER['REQUEST_URI'], 1);
}

/**
 * Form submit handler: photo approval form
 */
function bxdev_project_photo_approval_form_submit($form, &$form_state){
	$nid = arg(1);
	$values = $form_state['values'];
	// clear all values for current node
	db_delete('project_photos_approval')
		->condition('nid', $nid)
		->execute();
	// store each new value
	foreach($values as $key => $value){
		if(is_numeric($key)){
			if($value){
				db_insert('project_photos_approval')
					->fields(array(
						'nid' => $nid,
						'fid' => $key,
					))
					->execute();
			}
		}
	}
	drupal_set_message('Photo approvals have been updated.');
}

/**
 * Form validation handler: comment node form
 */
function bxdev_project_comment_node_form_validate($form, &$form_state){
	$values = $form_state['values'];
	// set the node title
	$comment = $values['field_comment']['und'][0]['value'];
	$title = substr($comment, 0, 100);
	form_set_value($form['title'], $title, $form_state);
	// set the project ref
	$project_nid = arg(1);
	$form['field_project_ref']['#parents'] = array('field_project_ref', 'und', 0, 'nid');
	form_set_value($form['field_project_ref'], $project_nid, $form_state);		
}

/**
 * Form validation handler: photo approval form
 */
function bxdev_project_photo_approval_form_validate($form, &$form_state){
	$values = $form_state['values'];
	$count = 0;
	// cycle through each photo and allow no more than eight choices
	foreach($values as $key => $value){
		if(is_numeric($key)){
			$count += $value;
		}
	}
	// check if greater than 8
	if($count > 8){
		form_error($form, 'A maximum of 8 choices can be approved.');
		return FALSE;
	}
}


/**
 * CUSTOM
 */

/**
 * Page callback: photo approval
 */
function bxdev_project_photo_approval_page($nid){
	$project_path = drupal_lookup_path('alias', 'node/' . $nid);
	$output = '<a href="/' . $project_path . '">Back to project</a>';
	$output .= render(drupal_get_form('bxdev_project_photo_approval_form'));
	return $output;
}

/**
 * Menu callback: project claim
 */
function bxdev_project_claim_callback($node){
	global $user;
	$node->field_pc_ref['und'][0]['uid'] = $user->uid;
	node_save($node);
	$project = new Project($node->nid);
	if(!$project->overridden){
		$project->set_status(2);
		$project->log('admin', 'Project auto updated to 2 - Claimed');
	}
	drupal_goto('projects/master');
}

/**
 * Menu callback: reset client
 */
function bxdev_project_reset_client_callback($nid){
	$project = new Project($nid);
	$user = new User();
	$user->load($project->client->uid);
	$user->send_client_project_login($nid);
	drupal_set_message('Client login information has been reset and sent to the user.');
	drupal_goto($project->project_path);
}

/**
 * Menu callback: project approve
 */
function bxdev_project_approve_callback($nid){
	$project = new Project($nid);
	// set the approved value to 1 (TRUE)
	$project->project->field_approved['und'][0]['value'] = 1; 
	// save the node
	node_save($project->project);
	if(!$project->overridden){
		// set the status to 6 - Approved
		$project->set_status(6);
	}
	// send emails
	$project->send_approved();
	// log the action
	$project->log('admin', 'Project approved');
	// print a success message
	drupal_set_message('Project ' . $project->project->title . ' has been approved!');
	// redirect back to project
	drupal_goto($project->project_path);
}

/**
 * Menu callback: download production details
 */
function bxdev_project_download_production_details($node){
	
	header( 'Pragma: public' ); 
	header( 'Content-Type: application/msword' ); 
	header( 'Content-Disposition: attachment; filename="' . str_replace(' ', '_', strtolower($node->title)) .  '_production_details.doc"' );
	
	$output = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">';
	$output .= '<style type="text/css">
		body {font-family: Arial; font-size: 20px;}
		.field {margin-bottom: 20px;}
		.field-label {font-weight: bold;}
	</style>';
	$output .= '<body>';
	$output .= '<h1>' . $node->title . ' Production Details</h1>';
	$output .= render(field_view_field('node', $node, 'field_shoot_date'));
	$output .= render(field_view_field('node', $node, 'field_voice_over'));
	$output .= render(field_view_field('node', $node, 'field_voice_over_gender'));
	$output .= render(field_view_field('node', $node, 'field_owner_interview'));
	$output .= render(field_view_field('node', $node, 'field_script_notes'));
	$output .= render(field_view_field('node', $node, 'field_logo'));
	$output .= render(field_view_field('node', $node, 'field_photos'));
	$output .= render(field_view_field('node', $node, 'field_features_include'));
	$output .= render(field_view_field('node', $node, 'field_features_avoid'));
	$output .= render(field_view_field('node', $node, 'field_unique'));
	$output .= '</body>';
	$output .= '</html>';	
	
	print $output;	
}

/**
 * Return the production log per node
 */
function bxdev_project_get_production_log($nid){
	$results = db_query("SELECT DATE_FORMAT(DATE_ADD(date, INTERVAL 2 HOUR), '%c/%e/%y %l:%i%p') as date, message, user_uid FROM {production_log} WHERE project_nid = :nid", array(':nid' => $nid));
	$output = '';
	if($results->rowCount() > 0){
		foreach($results as $result){
			$user = user_load($result->user_uid);
			$output .= '<div class="log-row">';
			$output .= '<strong>' . strtolower($result->date) . ': ' . $user->field_name['und'][0]['value'] . '</strong><br />';
			$output .= $result->message;
			$output .= '</div>';
		}
	}
	return $output;
}


/**
 * CLASSES
 */

/**
 * Contains all information related to a single project
 */
class Project {
	
	var $project;
	var $project_path;
	var $business;
	var $client;
	var $videographer;
	var $pc;
	var $sales;
	var $comments;
	var $overridden;
	
	/**
	 * Load a new Project and set all initial variables.
	 *
	 * @param $nid (int)
	 *   The nid of the project node
	 */
	function __construct($nid){
		// load the users
		$project = node_load($nid);
		$business = node_load($project->field_project_business_ref['und'][0]['nid']);
		$client = user_load($business->field_client_ref['und'][0]['uid']);
		$sales = user_load($project->uid);
		$pc = '';
		$videographer = '';
		// if pc has been assigned to the project
		if(!empty($project->field_pc_ref)){
			$pc = user_load($project->field_pc_ref['und'][0]['uid']);
		}
		// if videographer has been assigned to the project
		if(!empty($project->field_videog_ref)){
			$videographer = user_load($project->field_videog_ref['und'][0]['uid']);
		}
		// assign all intitial properties
		$this->project = $project;
		$this->project_path = drupal_lookup_path('alias', 'node/' . $this->project->nid);
		$this->business = $business;
		$this->client = $client;
		$this->sales = $sales;		
		$this->pc = $pc;
		$this->videographer = $videographer;		
		$this->comments = $this->get_comments();
		$this->overridden = $project->field_status_override['und'][0]['value'];
	}
	
	/**
	 * Log an action performed on or by the Project.
	 *
	 * @param $type (string)
	 *   The type of action to log
	 *
	 * @param $message (string)
	 *   The message to log with the action.
	 */
	function log($type, $message){
		global $user;
		// get the user role
		$role = bxdev_user_get_role($user->uid);
		// store in db
		db_insert('production_log')
			->fields(array(
				'project_nid' => $this->project->nid,
				'business_nid' => $this->business->nid,
				'client_uid' => $this->client->uid,
				'user_uid' => $user->uid,
				'user_role' => $role,
				'type' => $type,
				'message' => $message,
			))
			->execute();
	}
	
	/**
	 * Set the status of the Project.
	 *
	 * @param $id (int)
	 *   The id of the status (1 - 7)
	 */
	function set_status($id){
		$this->project->field_status['und'][0]['value'] = $id;
		$this->project->field_status_date['und'][0]['value'] = time();
		node_save($this->project);
	}
	
	/**
	 * Get the current status of a Project.
	 *
	 * @return int
	 */
	function get_status(){
		return $this->project->field_status['und'][0]['value'];
	}
	
	/**
	 * Get all users associated with a Project.
	 *
	 * @return array
	 */	
	function get_users(){
		$users = array();
		if(!empty($this->client)){
			$users[$this->client->uid] = $this->client;
		}
		if(!empty($this->pc)){
			$users[$this->pc->uid] = $this->pc;
		}
		if(!empty($this->videographer)){
			$users[$this->videographer->uid] = $this->videographer;
		}
		if(!empty($this->sales)){
			$users[$this->sales->uid] = $this->sales;
		}
		return $users;		
	}
	
	/**
	 * Notify all appropriate users when a comment has been posted.
	 *
	 * @param $cid (int)
	 *   The nid of the comment node
	 */
	function comment_notify($cid){
		global $base_url;
		// construct the project link
		$project_link = $base_url . '/' . $this->project_path;
		// load the comment node object
		$comment = node_load($cid);
		// get the poster's uid
		$owner_uid = $comment->uid;
		// get the sales user's uid
		$sales_uid = $this->sales->uid;
		// get all users associated with Project
		$users = $this->get_users();
		// remove the poster
		unset($users[$owner_uid]);
		// remove the sales user
		unset($users[$sales_uid]);
		foreach($users as $uid => $user){
			$comment_author = user_load($comment->uid);
			$comment_author = $comment_author->field_name['und'][0]['value'];
			// set all params to pass to the email message
			$params = array();
			$params['project_title'] = $this->project->title;
			$params['project_link'] = $project_link;
			$params['comment_author'] = $comment_author;
			$params['comment_date'] = date('m-d-Y', $comment->created);
			$params['comment'] = $comment->field_comment['und'][0]['value'];
			drupal_mail('bxdev_project', 'comment', $user->mail, language_default(), $params);
		}
	}

	/**
	 * Get all comments that belong to a Project.
	 *
	 * @return array
	 */
	function get_comments(){
		$comments = array();
		$results = db_query("SELECT entity_id FROM {field_data_field_project_ref} WHERE field_project_ref_nid = :nid", array(':nid' => $this->project->nid));
		if($results->rowCount() > 0){
			foreach($results as $result){
				$comment = node_load($result->entity_id);
				$comments[$comment->nid] = $comment;
			}
		}
		return $comments;
	}
	
	/**
	 * Send an email to the Client containing login and project info.
	 */
	function send_client_login(){
		drupal_mail('bxdev_project', 'first_comment', $this->client->mail, language_default(), array('project_path' => $this->project_path));
		$this->log('admin', 'Client sent login information');
	}
	
	/**
	 * Notify all appropriate users when a Project has been approved.
	 */
	function send_approved(){
		global $base_url;
		// build the project link
		$project_link = $base_url . '/' . $this->project_path;
		// build a list of email addresses (pc, sales, and client)
		$emails = $this->pc->mail . ', ' . $this->sales->mail . ', ' . $this->client->mail;
		// build params to pass to the email message
		$params = array(
			'project_title' => $this->project->title,
			'project_link' => $project_link,
		);
		$params = array(
			'project_title' => $this->project->title,
			'project_link' => $project_link,			
			'pc' => array(
				'full_name' => $this->pc->field_name['und'][0]['value'],
				'email' => $this->pc->mail,
				'phone' => $this->pc->field_phone['und'][0]['value'],
			),
		);		
		drupal_mail('bxdev_project', 'approved', $emails, language_default(), $params);
	}
	
	/**
	 * Get all approved photos associated with a Project.
	 *
	 * @return array
	 */
	function get_approved_photos(){
		$results = db_query("SELECT fid FROM {project_photos_approval} WHERE nid = :nid", array(':nid' => $this->project->nid));
		$approved_photos = array();
		if($results->rowCount() > 0){
			foreach($results as $row){
				$approved_photos[] = $row->fid;
			}
		}
		return $approved_photos;
	}

}
















