<?php

module_load_include('inc', 'bxdev_partner', 'bxdev_partner.forms');

/**
 * HOOKS
 */

/**
 * Implements hook_custom_theme().
 */
function bxdev_partner_custom_theme() {
	$uri = $_SERVER['REQUEST_URI'];
	if(strpos($uri, '/partner/') === 0){
  	return 'partner';
	}
}

/**
 * Implements hook_theme().
 */
function bxdev_partner_theme($existing, $type, $theme, $path) {
  return array(
    'bxdev_partner_order_form' => array(
			'render element' => 'form',
      'template' => 'order-form',
			'path' => drupal_get_path('module', 'bxdev_partner') . '/templates',
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 */
function bxdev_partner_preprocess_page(&$vars) {
	$node = $vars['node'];
	$vars['partner_logo'] = theme('image_style', array('path' => $node->field_partner_logo['und'][0]['uri'], 'style_name' => 'partner_logo'));
	$vars['partner_form'] = render(drupal_get_form('bxdev_partner_order_form'));
}


