<?php

module_load_include('inc', 'bxdev_payment', 'bxdev_payment.forms');

/**
 * HOOKS
 */

/**
 * Implements hook_menu().
 */
function bxdev_payment_menu() {
	
  $items['sales/add/cc'] = array(
    'title' => t('Create a New Video Project'),
		'page callback' => 'bxdev_payment_client_payment_step_one_page',
    'access arguments' => array('add new project'),
    'type' => MENU_CALLBACK,
  );

	$items['sales/add/cc-test'] = array(
	  'title' => t('Create a New Video Project'),
	  'page callback' => 'credit_card_test',
	  'access arguments' => array('add new project'),
	  'type' => MENU_CALLBACK,
	);

  return $items;
}

/**
 * Implements hook_user_delete().
 */
function bxdev_payment_user_delete($account) {
  db_delete('users_auth')
    ->condition('uid', $account->uid)
    ->execute();
}


/**
 * CUSTOM
 */

/**
 * Page callback: client payment step one
 */
function bxdev_payment_client_payment_step_one_page(){
	
	drupal_add_js(drupal_get_path('module', 'bxdev_payment') . '/bxdev_payment.js');
	
	$output = '<h2><strong>Client Payment Info</strong> (step 1 of 3)</h2>';
	
	$output .= render(drupal_get_form('bxdev_payment_project_client_credit_card_form'));
	
	return $output;
	
}
