<?php

/**
 * HOOKS
 */

/**
 * Implements hook_menu().
 */
function bxdev_user_menu() {
  $items['admin/user/create'] = array(
    'title' => 'Create new user',
    'page callback' => 'bxdev_user_create_user_page',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
  );

	$items['user/change/password'] = array(
		'title' => t('Change password'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('bxdev_user_change_password_form'),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

  return $items;
}

/**
 * Implements hook_user_insert().
 */
function bxdev_user_user_presave(&$edit, $account, $category) {
	// if new user, set the first time login flag
	if(!isset($edit['data']['first_time_login'])){
  	$edit['data']['first_time_login'] = 1;
	}
}

/**
 * Implements hook_user_login().
 */
function bxdev_user_user_login(&$edit, $account) {
	// if first time login
	if($account->data['first_time_login']){
		drupal_set_message('This is your first time logging in. Please change your password!');
		drupal_goto('user/change/password');
	}
}

/**
 * Implements hook_mail().
 */
function bxdev_user_mail($key, &$message, $params) {
	global $base_url;
	switch($key){
		case 'videographer':
			$subject = t('Thanks for becoming a Videographer!');
		  $body = 'You have been entered into the database.
		
			Here is your password: <strong>' . $params['pass'] . '</strong>';
			
		  $message['subject'] = t('Thanks for becoming a Videographer!');
		  $message['body'][] = $body;
			break;
			
		case 'sales':
			$subject = t('Your Sales account details for lightswitch.com');
		  $body = 'Click <a href="' . $base_url . '/user">' . $base_url . '/user</a> to login using the information below.
	
			Username: ' . $params['name'] . '<br />
			Password: ' . $params['pass'] . '';
		
		  $message['subject'] = $subject;
		  $message['body'][] = $body;
			break;
		
	}
}


/**
 * FORMS
 */

/**
 * Form builder: user create
 */
function bxdev_user_create_user_form($form, $form_state){
	$form['email'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Email'),
	  '#description' => t('<p>This will act as the username.</p><p>An email will automatically be sent to user with a temporary password.</p>'),
	);
	
	$form['role'] = array(
	  '#type' => 'radios',
	  '#title' => t('Role'),
	  '#options' => array(
			7 => 'Sales',
		),
	  '#default_value' => 7,
	);
	
	$form['create'] = array(
	  '#type' => 'submit',
	  '#value' => t('Create user'),
	);	
	
	return $form;	
}

/**
 * Form builder: change password
 */
function bxdev_user_change_password_form($form, $form_state){
	$form['pass'] = array(
		'#type' => 'password_confirm',
	);

	$form['submit'] = array(
	  '#type' => 'submit',
	  '#value' => t('Change password'),
	);	
	
	return $form;
}

/**
 * Form submit handler: user create
 */
function bxdev_user_create_user_form_submit($form, &$form_state){
	$values = $form_state['values'];
	$email = $values['email'];
	
	// check if valid email address
	if(!valid_email_address($email)){
		drupal_set_message('Please enter a valid email address.', 'error');
		return;
	}
	
	// check if user exists
	$user = user_load_by_name($email);
	if(!$user){
		// create the user
		$user = new User($email, 'sales');
		drupal_set_message('User ' . $user->name . ' has been created.');
	}else{
		drupal_set_message('User already exists. Please enter a new email address.', 'error');
	}
}

/**
 * Form submit handler: change password
 */
function bxdev_user_change_password_form_submit($form, &$form_state){
	global $user;
	// get the new password
	$pass = $form_state['values']['pass'];
	$edit = (array)$user;
	// save new password
	$edit['pass'] = $pass;
	// set the first time login flag to 0 (off)
	$edit['data']['first_time_login'] = 0;
	user_save($user, $edit);
	drupal_set_message('Your password has been saved!');
	drupal_goto('user/' . $user->uid);
}

/**
 * CUSTOM
 */

/**
 * Page callback: create user
 */
function bxdev_user_create_user_page(){
	$output = '';	
	$output .= drupal_render(drupal_get_form('bxdev_user_create_user_form'));	
	return $output;
}


class User{
	
	function __construct($email = NULL, $role = NULL){
		$this->password = user_password();
		// if arguments have been supplied
		if(!is_null($email) && !is_null($role)){
			$this->set_email($email);
			$this->set_role($role);
			$this->create();
			$this->send();
			$this->log();
			return $this->user;
		}
	}
	
	function create(){
		$edit = array(
			'name' => $this->name,
			'mail' => $this->name,
			'pass' => $this->password,
			'roles' => $this->roles,
			'status' => 1,
		);
		$this->user = user_save(NULL, $edit);
		// return $this->user;
	}
	
	function set_email($email){
		$this->name = $email;
		$this->mail = $email;
	}
	
	function set_role($role){
		switch($role){
			case 'sales':
				$this->roles = array(2 => 'authenticated user', 6 => 'sales');
				$this->role = 'sales';
				break;
			
			case 'client':
				$this->roles = array(2 => 'authenticated user', 7 => 'client');
				$this->role = 'client';
				break;	
		}	
	}
	
	function send(){
		drupal_mail('bxdev_user', $this->role, $this->user->mail, language_default(), array('name' => $this->user->name, 'pass' => $this->password));
	}
	
	function log(){
		switch($this->role){
			case 'sales':
				watchdog('pc', 'New sales: @name, uid: @uid', array('@name' => $this->user->name, '@uid' => $this->user->uid));
				break;
				
			case 'client':
				watchdog('sales', 'New client: @name, uid: @uid', array('@name' => $this->user->name, '@uid' => $this->user->uid));
				break;
		}
		
	}
	
}







