<?php

module_load_include('inc', 'bxdev_user', 'bxdev_user.forms');

/**
 * HOOKS
 */

/**
 * Implements hook_permission().
 */
function bxdev_user_permission() {
  return array(
    'view production details' =>  array(
      'title' => t('View production details'),
      'description' => t('View project production details.'),
    ),
	  'view production history' =>  array(
	    'title' => t('View production history'),
	    'description' => t('View project production history.'),
	  ),
		'change password' =>  array(
	    'title' => t('Change password'),
	    'description' => t('Change password.'),
	  ),
		'sales' =>  array(
	    'title' => t('Sales user permissions'),
	    'description' => t('Sales user permissions.'),
	  ),
		'pc' =>  array(
	    'title' => t('Production coordinator permissions'),
	    'description' => t('Production coordinator permissions.'),
	  ),
		'client' =>  array(
	    'title' => t('Client user permissions'),
	    'description' => t('Client user permissions.'),
	  ),
		'videographer' =>  array(
	    'title' => t('Videographer user permissions'),
	    'description' => t('Videographer user permissions.'),
	  ),
		'view project photos' =>  array(
	    'title' => t('View project photos'),
	    'description' => t('View project photos.'),
	  ),
		'upload business logo' =>  array(
		  'title' => t('Upload business logo'),
		  'description' => t('Upload business logo.'),
		),
		'upload videographer documents' =>  array(
		  'title' => t('Upload videographer documents'),
		  'description' => t('Upload videographer documents.'),
		),
		'add new project' => array(
			'title' => t('Add a new project'),
			'description' => t('Add a new project.'),
		),
  );
}

/**
 * Implements hook_menu().
 */
function bxdev_user_menu() {
  $items['user/%user/new'] = array(
    'title' => 'Create new user',
    'page callback' => 'bxdev_user_create_user_page',
    // 'access arguments' => array('administer users'),
		'access arguments' => array(1),
		'access callback' => 'bxdev_user_create_user_access',
		'weight' => 50,
    'type' => MENU_LOCAL_TASK,
  );

	$items['user/change/password'] = array(
		'title' => t('Change password'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('bxdev_user_change_password_form'),
		'access arguments' => array('change password'),
		'type' => MENU_CALLBACK,
	);
	
	$items['user/%/password/forgot'] = array(
		'page callback' => 'bxdev_user_password_forgot',
		'page arguments' => array(1),
		'access arguments' => array('change password'),
		'type' => MENU_CALLBACK,
	);
	
	$items['user/accept-terms'] = array(
		'page callback' => 'drupal_get_form',
		'page arguments' => array('bxdev_user_accept_terms_form'),
		'access arguments' => array('videographer'),
		'type' => MENU_CALLBACK,
	);

  return $items;
}

/**
 * Implements hook_user_insert().
 */
function bxdev_user_user_presave(&$edit, $account, $category) {
	// if new user, set the first time login flag
	if(!isset($edit['data']['first_time_login'])){
  	$edit['data']['first_time_login'] = 1;
	}
}

/**
 * Implements hook_user_login().
 */
function bxdev_user_user_login(&$edit, $account) {
	// if first time login
	bxdev_user_first_time_login_check($account);
	
	// if first time login does not redirect user, check for terms acceptance
	bxdev_user_terms_accept_check($account);
	
	if(isset($_GET['url']) && $_GET['url'] != ''){
		$url = $_GET['url'];
		drupal_goto($url);
	}
	
	// drupal_goto('user/' . $account->uid);
}

/**
 * Implements hook_mail().
 */
function bxdev_user_mail($key, &$message, $params) {
	
	global $base_url;
	$email = bxdev_email_get_email_by_name($key);
	
	$message['subject'] = token_replace($email->subject, $params);
	$message['body'][] = token_replace($email->body, $params);
	
	$message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
	
	if(!empty($params['headers']['cc'])){
		$message['headers']['cc'] = $params['headers']['cc'];
	}
	
	if(!empty($params['headers']['bcc'])){
		$message['headers']['bcc'] = $params['headers']['bcc'];
	}
	
	// switch($key){
	// 	case 'videographer':
	// 		$subject = t('Thank you for your interest in becoming a Lightswitch videographer!');
	// 		$body = 'Dear ' . $params['full_name'] . '!<br><br>';
	// 	  $body .= 'Thank you for your interest in becoming a lightswitch videographer! We have received your submission and are currently reviewing your information. Below you will find a unique username and password needed to access your videographer profile page on Lightswitch.com. If you would like to update your profile or make any changes you can do so by clicking the Login link.<br><br>';
	// 		$body .= 'Login link: <a href="' . $base_url . '/user">' . $base_url . '/user</a><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br><br>';
	// 		$body .= 'Feel free to reach out to us at production@lightswitch.com with any questions.<br><br>';
	// 		$body .= 'Thanks!<br>';
	// 		$body .= 'Team Lightswitch';
	// 		
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 	
	// 	case 'videographer_existing':
	// 		$subject = t('Thank you for your interest in becoming a Lightswitch videographer!');
	// 		$body = 'Hi ' . $params['full_name'] . '!<br><br>';
	// 	  $body .= 'Thank you for recently submitting your application to be a lightswitch videographer. We\'d like to let you know that the new lightswitch website is now up and running! It features an expanded videographer page that will let you update and edit your profile with new equipment, contact, or general info.  Our review process has a heavy emphasis on the type of equipment you currently own and operate.  Please be as detailed as possible.<br><br>';
	// 		$body .= 'Also, we have an exciting nationwide project that requires very specific equipment.  If you have a 7D or comparable camera, an off -board recorder (tascam, edirol), and a lav mic please fill out your videographer profile page and send an email to production@lightswitch.com . <strong>If you don\'t have this equipment, don\'t worry about it, you may still be qualified for other lightswitch productions.</strong><br><br>';
	// 		$body .= 'Below you will find the unique username and password needed to access your videographer profile page on lightswitch.com. Please click the Login link to get started!<br><br>';
	// 		$body .= 'Login link: <a href="' . $base_url . '/user">' . $base_url . '/user</a><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br><br>';
	// 		$body .= 'Feel free to reach out to us at production@lightswitch.com with any questions.<br><br>';
	// 		$body .= 'Thanks!<br>';
	// 		$body .= 'Team Lightswitch';
	// 		
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'sales':
	// 		$subject = t('Your Sales account details for Lightswitch');
	// 	  $body = 'Click <a href="' . $base_url . '/user">' . $base_url . '/user</a> to login using the information below.<br><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '';
	// 	
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'pc':
	// 		$subject = t('Your Production Coordinator account details for Lightswitch');
	// 	  $body = 'Click <a href="' . $base_url . '/user">' . $base_url . '/user</a> to login using the information below.<br><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '';
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 	
	// 	// NOT USED
	// 	case 'client':
	// 		$subject = t('Your Client account details for Lightswitch');
	// 	  $body = 'Click <a href="' . $base_url . '/user">' . $base_url . '/user</a> to login using the information below.<br><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '';
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 
	// 	case 'client_reset':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Dear ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'Thank you again for choosing Lightswitch to help with your online marketing efforts. Our production team has completed the first version of your video and we\'d love for you to review it. To watch your video, please login on Lightswitch.com using the username and password below:<br><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br>';
	// 		$body .= 'Video landing page: <a href="' . $base_url . '/' . $params['project_path'] . '">' . $base_url . '/' . $params['project_path'] . '</a><br><br>';
	// 		$body .= 'As a valued Lightswitch client, you receive one free round of video edits. If you’d like changes made to your video, login  and fill out all requested changes in the "Post a comment" field under your video. Please make all of your requests very specific so we can work to get your lightswitch video exactly how you want it.  Please note: After the first set of revisions, every additional round of edits will cost $50.<br><br>';
	// 		$body .= 'If you are happy with the video in its current form, please click “approve” on the video landing page below and we’ll send you the final product in convenient file formats.<br><br>';
	// 		$body .= 'Contact us with any questions or concerns.<br><br>';
	// 		$body .= 'Sincerely,<br>';
	// 		$body .= $params['pc']['full_name'] . '<br>';
	// 		$body .= $params['pc']['email'] . '<br>';
	// 		$body .= $params['pc']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'direct_sale_new':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Dear ' . $params['full_name'] . ',<br><br>';
	// 				  $body .= 'Thank you again for choosing Lightswitch to help with your online marketing efforts! Our production team has completed the first version of your video and we\'d love for you to review it. To watch your video, please login on Lightswitch.com using the username and password below:<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br>';
	// 		$body .= 'As a valued Lightswitch client, you receive one free round of video edits. If you\'d like changes made to your video, log in and post revisions in the "Post a comment" field under your video. You have 5 days to submit revision requests, after which the video will be considered approved as is.  Please make all of your requests very specific so we can work to get your Lightswitch video exactly how you want it. Please note: After the first set of revisions, every additional round of edits will cost $50.<br><br>';
	// 		$body .= 'If you are happy with the video in its current form, please click "approve" on the video landing page after you log in, and we\'ll send you the final product in convenient file formats.<br><br>';
	// 		$body .= 'Do not reply to this email; if you have questions please contact me via the information below!.<br><br>';
	// 		$body .= 'Sincerely,<br>';
	// 		$body .= $params['pc']['full_name'] . '<br>';
	// 		$body .= $params['pc']['email'] . '<br>';
	// 		$body .= $params['pc']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'direct_sale_existing':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Dear ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'Thank you again for choosing Lightswitch to help with your online marketing efforts! Our production team has completed the first version of your video and we\'d love for you to review it. To watch your video, please login on Lightswitch.com:<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br><br>';
	// 		$body .= 'As a valued Lightswitch client, you receive one free round of video edits. If you\'d like changes made to your video, log in and post revisions in the "Post a comment" field under your video. You have 5 days to submit revision requests, after which the video will be considered approved as is.  Please make all of your requests very specific so we can work to get your Lightswitch video exactly how you want it. Please note: After the first set of revisions, every additional round of edits will cost $50.<br><br>';
	// 		$body .= 'If you are happy with the video in its current form, please click "approve" on the video landing page after you log in, and we\'ll send you the final product in convenient file formats.<br><br>';
	// 		$body .= 'Do not reply to this email; if you have questions please contact me via the information below!.<br>';
	// 		$body .= 'Sincerely,<br>';
	// 		$body .= $params['pc']['full_name'] . '<br>';
	// 		$body .= $params['pc']['email'] . '<br>';
	// 		$body .= $params['pc']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'business_dev_new':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Dear ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'Thank you again for choosing Lightswitch to help with your online marketing efforts! Our production team has completed the first version of your video and we\'d love for you to review it. To watch your video, please login on Lightswitch.com using the username and password below:<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br>';
	// 		$body .= 'Sincerely,<br>';
	// 		$body .= $params['pc']['full_name'] . '<br>';
	// 		$body .= $params['pc']['email'] . '<br>';
	// 		$body .= $params['pc']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 
	// 	case 'business_dev_existing':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Dear ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'Thank you again for choosing Lightswitch to help with your online marketing efforts! Our production team has completed the first version of your video and we\'d love for you to review it. To watch your video, please login on Lightswitch.com:<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br><br>';
	// 		$body .= 'Sincerely,<br>';
	// 		$body .= $params['pc']['full_name'] . '<br>';
	// 		$body .= $params['pc']['email'] . '<br>';
	// 		$body .= $params['pc']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;		
	// 
	// 	case 'spec_new':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Hello ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'A lightswitch videographer was in ' . $params['business'] . ' a couple of weeks ago to capture footage of your business. Your video is complete and ready for your viewing! If you are interested in purchasing the video you would be able to make a round of edits/changes to the video as you wish. We would also remove all lightswitch branding from the final version and send you the video in easy to download file formats. You would own full rights to your video and can use it on any of your online marketing pages. The video is a one time fee of only $299!<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '<br>';
	// 		$body .= 'Please review the video and let me know what you think!<br><br>';
	// 		$body .= $params['sales']['full_name'] . '<br>';
	// 		$body .= $params['sales']['email'] . '<br>';
	// 		$body .= $params['sales']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 
	// 	case 'spec_existing':
	// 		$subject = t('Your Lightswitch video is ready for review!');
	// 		$body = 'Hello ' . $params['full_name'] . ',<br><br>';
	// 	  $body .= 'A lightswitch videographer was in ' . $params['business'] . ' a couple of weeks ago to capture footage of your business. Your video is complete and ready for your viewing! If you are interested in purchasing the video you would be able to make a round of edits/changes to the video as you wish. We would also remove all lightswitch branding from the final version and send you the video in easy to download file formats. You would own full rights to your video and can use it on any of your online marketing pages. The video is a one time fee of only $299!<br><br>';
	// 		$body .= '<a href="' . $base_url . '/user?url=' . $params['project_path'] . '">Click here to see your video!</a><br><br>';
	// 		$body .= 'Please review the video and let me know what you think!<br><br>';
	// 		$body .= $params['sales']['full_name'] . '<br>';
	// 		$body .= $params['sales']['email'] . '<br>';
	// 		$body .= $params['sales']['phone'];
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 		
	// 	case 'password_reset':
	// 		$subject = t('Your Lightswitch password has been reset');
	// 	  $body = 'Click <a href="' . $base_url . '/user">' . $base_url . '/user</a> to login using the information below.<br><br>';
	// 		$body .= 'Username: ' . $params['name'] . '<br>';
	// 		$body .= 'Password: ' . $params['pass'] . '';
	// 
	// 	  $message['subject'] = $subject;
	// 	  $message['body'][] = $body;
	// 		break;
	// 	
	// }
	// $message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
}

/**
 * Implementation of hook_menu_local_tasks_alter().
 */
function bxdev_user_menu_local_tasks_alter(&$data, $router_item, $root_path){
	// dpm($data);
	// if user profile page
	if(arg(0) == 'user' && is_numeric(arg(1))){
		$user = user_load(arg(1));
		// pc
		if(isset($user->roles[4])){
			$data['tabs'][0]['output'][0]['#link']['title'] = 'Your Projects';
			$data['tabs'][0]['output'][1]['#link']['title'] = 'Account info';
			unset($data['tabs'][1]);	
		// videographer
		}else	if(isset($user->roles[5])){
			if(!empty($data['tabs'][0])){
				$data['tabs'][0]['output'][0]['#link']['title'] = 'Your Projects';
				$data['tabs'][0]['output'][1]['#link']['title'] = 'Account info';
				unset($data['tabs'][0]['output'][1]);
				// dpm($data);
			}
			if(!empty($data['tabs'][1])){
				$data['tabs'][1]['output'][0]['#link']['title'] = 'Account settings';
				$data['tabs'][1]['output'][1]['#link']['title'] = 'Videographer details';
			}
		// sales
		}else	if(isset($user->roles[6])){
			$data['tabs'][0]['output'][0]['#link']['title'] = 'Your Projects';
			$data['tabs'][0]['output'][1]['#link']['title'] = 'Account info';		
		// client
		}else if(isset($user->roles[7])){
			$data['tabs'][0]['output'][0]['#link']['title'] = 'Your Projects';
			$data['tabs'][0]['output'][1]['#link']['title'] = 'Account info';			
		}
	}else if(arg(0) != 'admin'){
		// unset($data['tabs']);
	}
	
	// get the logged in user
	global $user;
	// if user is pc and viewing a videographer profile page
	if(bxdev_user_get_role($user->uid) == 'pc' && arg(2) == 'info'){
		// remove the user tabs
		unset($data['tabs']);
	}
	
}

/**
 * Implementation of hook_preprocess_user_profile(). 
 */
function bxdev_user_preprocess_user_profile(&$vars){
	$uid = arg(1);
	$user = user_load($uid);
	$output = '';
	// pc
	if(isset($user->roles[4])){
		$output .= '<div class="">';
		$output .= '<a href="/projects/master" class="add-project">Master project list</a> ';
		$output .= '<a href="/sales/add/business" class="add-project">+ Add project</a> ';
		$output .= '<a href="/sales/add/cc" class="add-project">+ Add project (cc)</a>&nbsp;&nbsp;&nbsp;&nbsp;';
		$output .= '<a class="add-project" href="/videographers">Videographers directory</a> ';
		$output .= '<a class="add-project" href="/admin/clients">Clients</a> ';
		$output .= '<a href="/admin/structure/types" class="add-project">Admin settings</a> ';
		$output .= '</div><br />';
		$output .= views_embed_view('projects', 'pc_landing', $vars['user']->uid, $vars['user']->uid);
	// videographer
	}else if(isset($user->roles[5])){
		$output .= views_embed_view('projects', 'block_2');
	// sales
	}else if(isset($user->roles[6])){
		$output .= views_embed_view('projects', 'block');
	// client
	}else if(isset($user->roles[7])){
		$output .= views_embed_view('projects', 'block_1');
	}
	$vars['user_profile'] = $output;
	
}

/**
 * Implements hook_preprocess_html().
 */
function bxdev_user_preprocess_html(&$variables) {
	global $user;
	$arg2 = arg(2);
	// if pc user and url is user/%
	if(bxdev_user_get_role($user->uid) == 'pc' && (arg(0) == 'user' && is_numeric(arg(1)) && !$arg2)){
		// add body class
		$variables['classes_array'][] = 'wide-table';
	}
}

/**
 * Implements hook_preprocess_page().
 */
function bxdev_user_preprocess_page(&$vars){
	global $user;
	$role = bxdev_user_get_role($user->uid);
	// if user page
	if(arg(0) == 'user' && is_numeric(arg(1))){
		$account = user_load(arg(1));
		// set the title
		drupal_set_title('Welcome, ' . $account->field_name['und'][0]['value']);
		
		// if user is pc and viewing a videographer profile page
		if($role == 'pc' && arg(2) == 'info'){
			drupal_set_title('Lightswitch Videographer Directory');
		}
	}	
}

/**
 * Implements hook_block_info().
 */
function bxdev_user_block_info() {
  $blocks['user_info']['info'] = 'User info';
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bxdev_user_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'user_info':
			global $user;
			$output = '';
			if($user->uid !== 0){
				$output .= '<div class="username">Logged in as ' . $user->name . '</div>';
				$output .= '<div class="actions"><a href="/user/' . $user->uid . '">Account</a> | <a href="/user/logout">Logout</a></div>';
			}else{
				$output .= '<a href="/user">Login</a>';
			}
      $block['content'] = $output;
      break;
  }
  return $block;
}

/**
 * Implements hook_views_query_alter().
 */
function bxdev_user_views_query_alter(&$view, &$query){
	if($view->name == 'projects' && $view->current_display == 'pc_landing'){
		$query->where[1] = $query->where[0];
		array_shift($query->where[1]['conditions']);
		$query->where[1]['type'] = 'OR';
		unset($query->where[0]['conditions'][1], $query->where[0]['conditions'][2]);
	}
}

/**
 * CUSTOM
 */

/**
 * Page callback: create user
 */
function bxdev_user_create_user_page(){
	$output = '';	
	$output .= drupal_render(drupal_get_form('bxdev_user_create_user_form'));	
	return $output;
}

/**
 * Page callback: password forgot
 */
function bxdev_user_password_forgot($uid){
	$user = new User();
	$user->load($uid);
	$user->send_password_reset();
	drupal_set_message('A new password has been sent to your email. You must log out to use your new password. Click <a href="/user/logout">here</a> to logout');
	drupal_goto('user/' . $uid . '/edit');
}

/**
 * Access callback: create new user
 */
function bxdev_user_create_user_access($account){
	global $user;
	return user_access('administer users') && $account->uid == $user->uid;
}

/**
 * Return user role
 */
function bxdev_user_get_role($uid){
	$user = user_load($uid);
	$roles = $user->roles;
	$role = 'authenticated user';
	if(array_key_exists(4, $roles)){
		$role = 'pc';
	}else if(array_key_exists(5, $roles)){
		$role = 'videographer';
	}else if(array_key_exists(6, $roles)){
		$role = 'sales';
	}else if(array_key_exists(7, $roles)){
		$role = 'client';
	}
	return $role;
}

/**
 * Converts existing Videographer nodes to users
 */
function bxdev_user_convert_videographer_nodes(){
	$results = db_query("SELECT nid FROM {node} WHERE nid = 884");
	foreach($results as $result){
		// load the node object
		$node = node_load($result->nid);
		// create a new videographer user
		$user = new User($node->field_email['und'][0]['email'], 'videographer', $node->title, $node->field_phone['und'][0]['value']);
		// load the user
		$user = $user->get_user();
		// create a new videographer profile
		$profile = profile_create(array('user' => $user, 'type' => 'videographer'));
		// assign all fields to profile
		$profile->field_region['und'][0]['value'] = $node->field_region['und'][0]['value'];
		$profile->field_address['und'][0]['value'] = $node->field_address['und'][0]['value'];
		$profile->field_transportation['und'][0]['value'] = $node->field_transportation['und'][0]['value'];
		$profile->field_skills['und'][0]['value'] = $node->field_skills['und'][0]['value'];
		$profile->field_equipment['und'][0]['value'] = $node->field_equipment['und'][0]['value'];
		$profile->field_links_work['und'][0]['value'] = $node->field_links_work['und'][0]['value'];
		$profile->field_availability['und'][0]['value'] = $node->field_availability['und'][0]['value'];
		$profile->field_rating['und'][0]['value'] = $node->field_rating['und'][0]['value'];
		$profile->field_notes['und'][0]['value'] = $node->field_notes['und'][0]['value'];
		$profile->field_resume['und'][0] = $node->field_resume['und'][0];
		// save the profile
		profile2_save($profile);
	}
}

/**
 * Check if user has accepted the terms and policies
 */
function bxdev_user_terms_accept_check($account){
	// check if videographer
	if(bxdev_user_get_role($account->uid) == 'videographer'){
		// load the user's profile		
		$profile = profile2_load_by_user($account, 'videographer');
		// check if videographer has accepted terms
		if(empty($profile->field_videographer_terms['und'][0]['value']) || $profile->field_videographer_terms['und'][0]['value'] == 0){
			drupal_goto('user/accept-terms');
		}
	}
}

/**
 * Check if first time login for user
 */
function bxdev_user_first_time_login_check($account){
	// if first time login
	if($account->data['first_time_login']){
		$options = array();
		// check for destination param
		if(isset($_GET['url'])){
			$options['query'] = array(
				'destination' => $_GET['url'],
			);
		}
		drupal_goto('user/change/password', $options);
	}
}


